version: '3.5'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "demo"
    volumes:
      - ./docker-init-db.sql:/docker-entrypoint-initdb.d/docker-init-db.sql
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network
    command: -p 5432

  redis-single-node-cluster:
    image: docker.io/bitnami/redis-cluster:7.0
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_CLUSTER_REPLICAS=0'
      - 'REDIS_NODES=127.0.0.1 127.0.0.1 127.0.0.1'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1'
    ports:
      - '6379:6379'

networks:
  postgres-compose-network:
    driver: bridge